### ISSUE TITLE
Funksjoner for å hente nødvendig info om legen

### ISSUE THREAD

**Issue by annvp** [navikt/sof#25]
- [x] HPR-nummer
- [x] Legens navn
- [ ] Sykehusets navn
- [ ] Sykehusets adresse
- [x] Legens telefonnummer

**Comment by Karolill** [comment]
Tenker vi gjør det slik at vi sender inn en referanse til legen (Practitioner) i questionnaireResponsePleiepenger.json. Her er navn og kontaktinfo lagret. Litt usikker på om HPR er lagret, men det kan jo ikke være lagret noe annet sted heller. 

Skal spørre Michael om det med sykehuset
